spring:
  datasource:
    ###set h2
    url: jdbc:h2:tcp://localhost/~/community
    driverClassName: org.h2.Driver
    username: sa
    password:

  security:
    jwt:
      header: Authorization
      #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 604800

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500 #100~1000

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  ##swagger 버전 맞추기
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
#    org.hibernate.SQL : debug
    org.hibernate.type : trace
    org:
      hibernate:
        engine:
          transaction:
            internal:
              TransactionImpl: debug

server:
  port: 8080
  servlet:
    context-path: /
    session:
      #timeout: 30m
      tracking-modes: cookie
    encoding:
      force-request: true
      force-response: true

property:
  file:
    dir: /Users/choisj/Desktop/choisj/etc/file_store